version: 2

sources:
  - name: supabase_uploads
    schema: public
    description: "Raw data uploaded via Python script"
    tables:
      - name: chargers
        description: "The main table containing all charger counts at all levels"
      - name: ev_registrations
        description: "The main table containing all ev registrations at all levels"
      - name: region_lookup
        description: "Reference for regions and their descendants"