name: EV Data Pipeline

on:
  schedule:
    - cron: '00 00 * * 2,5'
  workflow_dispatch:

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: "6543"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          # Specific engine needed for your pd.read_excel(engine='odf') calls
          pip install odfpy 

      - name: List models directory
        run: |
          echo "Current directory:"
          pwd
          echo "Files in models directory:"
          ls -R workflows/models/

      - name: Setup dbt Profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml
        
      - name: Run Python Pipeline
        run: python ev_pipeline.py
