name: EV Data Pipeline

on:
  schedule:
    - cron: '28 21 * * 1-6'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: "6543"
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          # Specific engine needed for your pd.read_excel(engine='odf') calls
          pip install odfpy 

      - name: Setup dbt Profile
        run: |
          mkdir -p ~/.dbt
          cat << 'EOF' > ~/.dbt/profiles.yml
          ev_project:
            outputs:
              dev:
                type: postgres
                host: "{{ env_var('DB_HOST') }}"
                user: "{{ env_var('DB_USER') }}"
                password: "{{ env_var('DB_PASSWORD') }}"
                port: 6543
                dbname: postgres
                schema: public
                threads: 1
            target: dev
          EOF

      - name: Run Python Pipeline
        run: python ev_pipeline.py
